theme: jekyll-theme-midnight

title: bradipao.net
google_analytics: 257522145

# Build settings
# markdown:    kramdown
# highlighter: rouge

# Markdown Processors
# kramdown:
#   input: GFM
#   auto_ids: true
#   syntax_highlighter: rouge
